/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_ThreadNumber */

#ifndef _Included_com_test_ThreadNumber
#define _Included_com_test_ThreadNumber
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_ThreadNumber
 * Method:    setNumber
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_test_ThreadNumber_setNumber
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_test_ThreadNumber
 * Method:    getNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_test_ThreadNumber_getNumber
  (JNIEnv *, jobject);

/*
 * Class:     com_test_ThreadNumber
 * Method:    fromJNI
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_test_ThreadNumber_fromJNI
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
