/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_JniThreadTestActivity */

#ifndef _Included_com_test_JniThreadTestActivity
#define _Included_com_test_JniThreadTestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_JniThreadTestActivity
 * Method:    mainThread
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_test_JniThreadTestActivity_mainThread
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_test_JniThreadTestActivity
 * Method:    setJNIEnv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_test_JniThreadTestActivity_setJNIEnv
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
